name: Manual build push at main
on:  
  workflow_dispatch:
jobs:
  build_push:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - run: |
          echo $(git log | grep -P "commit [a-z0-9]{40}" -m 1 | cut -d ' ' -f2 | git log --format=%B -n 1)
      - name: Malevich Actions
        uses: MalevichAI/auto-ci@v0.2.0
        with:
          registry: 'ecr'
          registry_url: ${{ secrets.REGISTRY_URL }}
          registry_id: ${{ secrets.REGISTRY_ID }}
          username: ${{ secrets.IMAGE_USERNAME }}
          password: ${{ secrets.IMAGE_PASSWORD }}
          space_username: ${{ secrets.SPACE_USERNAME }}
          space_password: ${{ secrets.SPACE_PASSWORD }}
          api_url: ${{ secrets.API_URL }}
          region: 'us-east-1'
